version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=meltano
      - POSTGRES_USER=meltano
      - POSTGRES_DB=meltano

volumes:
  pgdata: